version: "3.7"

services:
  sample:
    container_name: sample
    image: sampleapi
    ports:
      - "8000:80"
    networks:
      - net-sample-local

  interview-test-server:
    container_name: interview-test-server
    image: ptsdocker16/interview-test-server
    ports:
      - "5001:5000"
    networks:
      - net-sample-local

networks:
  net-sample-local:
      driver: bridge